# Generated by Django 3.0.1 on 2019-12-26 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0003_auto_20191225_1659'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='file',
        ),
    ]
